package org.twbraam.processor.threads.sources

import java.io.Serializable
import java.sql.Timestamp
import java.util


@SerialVersionUID(1L)
final class Predef private(val bounded: Boolean) extends util.Iterator[String] with Serializable {
  private var index: Int = 0
  private var timestamp: Long = Predef.INITIAL_TIMESTAMP.getTime

  override def hasNext: Boolean =
    if (index < Predef.data.size) true
    else if (!bounded) {
      index = 0
      true
    }
    else false

  override def next: String = {
    Thread.sleep(200)
    Predef.data({index += 1; index - 1})
  }
}


@SerialVersionUID(1L)
object Predef {
  private val INITIAL_TIMESTAMP: Timestamp = Timestamp.valueOf("2019-01-01 00:00:00")
  private val SIX_MINUTES: Long = 6 * 60 * 1000

  private[threads] def bounded: Predef = new Predef(true)

  private[threads] def unbounded: Predef = new Predef(false)

  private val data: List[String] = List(
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Keep buying guys. We have to go over 30,id=t3_l9bizq,link=https://www.reddit.com/r/dogecoin/comments/l9bizq/keep_buying_guys_we_have_to_go_over_30/,author=/u/ImArunShaji,date=2021-01-31T12:38:25Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Not oc,id=t3_l9bizo,link=https://www.reddit.com/r/IndianDankMemes/comments/l9bizo/not_oc/,author=/u/chocobun43,date=2021-01-31T12:38:25Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=New Pirate Dex Class: Mo Xuan (x3TheAran59 video),id=t3_l9bizn,link=https://www.reddit.com/r/Maplestory/comments/l9bizn/new_pirate_dex_class_mo_xuan_x3thearan59_video/,author=/u/AlphabeticaI,date=2021-01-31T12:38:25Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Deptford, South East London,id=t3_l9bizl,link=https://www.reddit.com/r/UrbanHell/comments/l9bizl/deptford_south_east_london/,author=/u/mywife-took-thekids,date=2021-01-31T12:38:24Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=من الصفحة الرابعة من كتاب الله إلى الصفحة السادسة | قليل دائم خير من كثير منقطع,id=t3_l9bizi,link=https://www.reddit.com/r/islam/comments/l9bizi/من_الصفحة_الرابعة_من_كتاب_الله_إلى_الصفحة_السادسة/,author=/u/hdd9000gb,date=2021-01-31T12:38:24Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Finish Him,id=t3_l9bizg,link=https://www.reddit.com/r/MortalShell/comments/l9bizg/finish_him/,author=/u/GerardoDunn965,date=2021-01-31T12:38:24Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Hassssssssss,id=t3_l9bizf,link=https://www.reddit.com/r/lanetli_resimler/comments/l9bizf/hassssssssss/,author=/u/activex7etki,date=2021-01-31T12:38:23Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=[World] - ‘Abrahamic’ conference in Dubai aims to further UAE-Israel business dialogue | Al Arabiya,id=t3_l9bizc,link=https://www.reddit.com/r/AutoNewspaper/comments/l9bizc/world_abrahamic_conference_in_dubai_aims_to/,author=/u/AutoNewspaperAdmin,date=2021-01-31T12:38:23Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Following 303AL’s lead. F**k these guys.,id=t3_l9biza,link=https://www.reddit.com/r/CovIdiots/comments/l9biza/following_303als_lead_fk_these_guys/,author=/u/AmIStillBanneddddd,date=2021-01-31T12:38:23Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=NHK「チアノーゼ、呼吸数25回/分、横になって呼吸が出来ず起きた状態での呼吸が出たら保健所に連絡を」 [445972832],id=t3_l9biz6,link=https://www.reddit.com/r/r_kenmou/comments/l9biz6/nhkチアノーゼ呼吸数25回分横になって呼吸が出来ず起きた状態での呼吸が出たら保健所に連絡を/,author=/u/i1256020,date=2021-01-31T12:38:23Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=A beautiful moment happened last night,id=t3_l9biz3,link=https://www.reddit.com/r/Gloomhaven/comments/l9biz3/a_beautiful_moment_happened_last_night/,author=/u/Stegenwashere,date=2021-01-31T12:38:22Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Message To Your Crush,id=t3_l9biyy,link=https://www.reddit.com/r/Crushes/comments/l9biyy/message_to_your_crush/,author=/u/smolbritishbean,date=2021-01-31T12:38:22Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=cursed_loot,id=t3_l9biyw,link=https://www.reddit.com/r/AssassinsCreedMemes/comments/l9biyw/cursed_loot/,author=/u/tony_mastria,date=2021-01-31T12:38:22Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=UAE vaccinates 71,710 people against COVID19 in past 24 hours,id=t3_l9biyr,link=https://www.reddit.com/r/dubai/comments/l9biyr/uae_vaccinates_71710_people_against_covid19_in/,author=/u/piplinkn,date=2021-01-31T12:38:21Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Very hard urge (pun intended),id=t3_l9biyn,link=https://www.reddit.com/r/NoFap/comments/l9biyn/very_hard_urge_pun_intended/,author=/u/sree7492,date=2021-01-31T12:38:20Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Brisbane Heat explode late in run chase to knock out Sydney Thunder in BBL finals,id=t3_l9biyg,link=https://www.reddit.com/r/ABCaus/comments/l9biyg/brisbane_heat_explode_late_in_run_chase_to_knock/,author=/u/GeorgeYDesign,date=2021-01-31T12:38:20Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Tim Cook May Have Just Ended Facebook,id=t3_l9biye,link=https://www.reddit.com/r/tech/comments/l9biye/tim_cook_may_have_just_ended_facebook/,author=/u/glowsplash,date=2021-01-31T12:38:20Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Sighs,id=t3_l9biyd,link=https://www.reddit.com/r/AIDungeon/comments/l9biyd/sighs/,author=/u/KompotBoss1991,date=2021-01-31T12:38:20Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=me_irl,id=t3_l9biy7,link=https://www.reddit.com/r/me_irl/comments/l9biy7/me_irl/,author=/u/These-Capital257,date=2021-01-31T12:38:19Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Questa l'ho fatto un paio de mesetti fa però ho voluto repostarla,id=t3_l9biy5,link=https://www.reddit.com/r/LaStalla/comments/l9biy5/questa_lho_fatto_un_paio_de_mesetti_fa_però_ho/,author=/u/Samuel3Ceccarelli,date=2021-01-31T12:38:19Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=عروض انصار جاليرى البحرين 1 حتى 10-2-2021 مهرجان #عروض_انصار_جاليرى_البحرين #العروض #el3rod #تخفيضات #خصومات #تسوق #عروض #تخفيض #خصم #عرض #اخر_عروض_البحرين #البحرين #عروض_البحرين,id=t3_l9biy4,link=https://www.reddit.com/r/el3rod_Bahrain/comments/l9biy4/عروض_انصار_جاليرى_البحرين_1_حتى_1022021_مهرجان/,author=/u/el3rod,date=2021-01-31T12:38:19Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Uhm why,id=t3_l9biy2,link=https://www.reddit.com/r/meme/comments/l9biy2/uhm_why/,author=/u/ProtectUreHead,date=2021-01-31T12:38:18Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Ate his words,id=t3_l9biy0,link=https://www.reddit.com/r/Valhala/comments/l9biy0/ate_his_words/,author=/u/SimeonAngelov,date=2021-01-31T12:38:18Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Greetings from Oberstdorf,id=t3_l9bixu,link=https://www.reddit.com/r/bavaria/comments/l9bixu/greetings_from_oberstdorf/,author=/u/1ance10t,date=2021-01-31T12:38:17Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Raikou raid on me adding first 10 stay online,id=t3_l9bixt,link=https://www.reddit.com/r/PokemonGoFriends/comments/l9bixt/raikou_raid_on_me_adding_first_10_stay_online/,author=/u/Inner-Local-9466,date=2021-01-31T12:38:17Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=My finasteride experience 19m,id=t3_l9bj1o,link=https://www.reddit.com/r/tressless/comments/l9bj1o/my_finasteride_experience_19m/,author=/u/Leventj7,date=2021-01-31T12:38:33Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=What langage I am reading ?,id=t3_l9bj1m,link=https://www.reddit.com/r/geoguessr/comments/l9bj1m/what_langage_i_am_reading/,author=/u/__CoLD,date=2021-01-31T12:38:33Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Fun Fact: This is what you get when you search drainage tunnel on google XD.,id=t3_l9bj1h,link=https://www.reddit.com/r/gtaonline/comments/l9bj1h/fun_fact_this_is_what_you_get_when_you_search/,author=/u/_Aws_,date=2021-01-31T12:38:33Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Most logical NF type?,id=t3_l9bj1g,link=https://www.reddit.com/r/mbti/comments/l9bj1g/most_logical_nf_type/,author=/u/Theasude,date=2021-01-31T12:38:32Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=68p is the MOS I want but out of school a year. Got 49 on Practice.,id=t3_l9bj1e,link=https://www.reddit.com/r/Militaryfaq/comments/l9bj1e/68p_is_the_mos_i_want_but_out_of_school_a_year/,author=/u/LogTossingGE,date=2021-01-31T12:38:32Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Android Auto OnePlus8 issues and my solution,id=t3_l9bj1b,link=https://www.reddit.com/r/oneplus/comments/l9bj1b/android_auto_oneplus8_issues_and_my_solution/,author=/u/marglexx,date=2021-01-31T12:38:31Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=My Happy Little Corner,id=t3_l9bj1a,link=https://www.reddit.com/r/setups/comments/l9bj1a/my_happy_little_corner/,author=/u/rafaelconde,date=2021-01-31T12:38:31Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Just sit back relax and smoke a Doobie !,id=t3_l9bj18,link=https://www.reddit.com/r/SpotifyPlaylists/comments/l9bj18/just_sit_back_relax_and_smoke_a_doobie/,author=/u/kaameshh,date=2021-01-31T12:38:31Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Daily rewards bug with new update 30/1,id=t3_l9bj16,link=https://www.reddit.com/r/nfsnolimits/comments/l9bj16/daily_rewards_bug_with_new_update_301/,author=/u/Icon-Post,date=2021-01-31T12:38:31Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=A new start (14M),id=t3_l9bj15,link=https://www.reddit.com/r/NoFap/comments/l9bj15/a_new_start_14m/,author=/u/nzxtrr,date=2021-01-31T12:38:31Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Having no color timer means Shin Ultraman will never have to worry about this happening,id=t3_l9bj13,link=https://www.reddit.com/r/Ultraman/comments/l9bj13/having_no_color_timer_means_shin_ultraman_will/,author=/u/BattleUpSaber,date=2021-01-31T12:38:31Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Speed up your slow computer same like the smart phone performance,id=t3_l9bj0y,link=https://www.reddit.com/r/SoftwareApps/comments/l9bj0y/speed_up_your_slow_computer_same_like_the_smart/,author=/u/Soft-Cleaner,date=2021-01-31T12:38:30Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=A missing TV episode,id=t3_l9bj0x,link=https://www.reddit.com/r/xmen/comments/l9bj0x/a_missing_tv_episode/,author=/u/iamazrock,date=2021-01-31T12:38:30Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Playing as Godzilla legitimately...kinda,id=t3_l9bj0r,link=https://www.reddit.com/r/DnD/comments/l9bj0r/playing_as_godzilla_legitimatelykinda/,author=/u/_pizzilla_,date=2021-01-31T12:38:29Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Let’s get past .035 by 8 am EST let’s go!!!,id=t3_l9bj0q,link=https://www.reddit.com/r/dogecoin/comments/l9bj0q/lets_get_past_035_by_8_am_est_lets_go/,author=/u/goonfish66,date=2021-01-31T12:38:29Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=AG-Systems Pure Theme By Akiddo #theme @themes3ds,id=t3_l9bj0p,link=https://www.reddit.com/r/themeplaza/comments/l9bj0p/agsystems_pure_theme_by_akiddo_theme_themes3ds/,author=/u/3dsthemesbot,date=2021-01-31T12:38:29Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Adorable,id=t3_l9bj0o,link=https://www.reddit.com/r/PetMice/comments/l9bj0o/adorable/,author=/u/Blood_Oleander,date=2021-01-31T12:38:29Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=pezzi di m****,id=t3_l9bj0l,link=https://www.reddit.com/r/MyheroacademiaITA/comments/l9bj0l/pezzi_di_m/,author=/u/Olli2007,date=2021-01-31T12:38:28Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Meanwhile in an alternate Universe....,id=t3_l9bj0i,link=https://www.reddit.com/r/Naruto/comments/l9bj0i/meanwhile_in_an_alternate_universe/,author=/u/altriascarlet18,date=2021-01-31T12:38:28Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Oneplus 8 loses hdmi support after oxygen OS update.,id=t3_l9bj0b,link=https://www.reddit.com/r/oneplus/comments/l9bj0b/oneplus_8_loses_hdmi_support_after_oxygen_os/,author=/u/tag420,date=2021-01-31T12:38:27Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=idk,id=t3_l9bj0c,link=https://www.reddit.com/r/Duklock/comments/l9bj0c/idk/,author=/u/SejrosXDD,date=2021-01-31T12:38:27Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=5 year partner here, sharing some of my latte art over the ages!,id=t3_l9bj09,link=https://www.reddit.com/r/starbucks/comments/l9bj09/5_year_partner_here_sharing_some_of_my_latte_art/,author=/u/paranrmalsmacktivity,date=2021-01-31T12:38:27Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=iCloud takes all the bandwidth,id=t3_l9bj06,link=https://www.reddit.com/r/applehelp/comments/l9bj06/icloud_takes_all_the_bandwidth/,author=/u/MachaMacha-O3O-,date=2021-01-31T12:38:27Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Heyo, I’m new to the game and searching for advice!,id=t3_l9bj05,link=https://www.reddit.com/r/GirlsxBattle2/comments/l9bj05/heyo_im_new_to_the_game_and_searching_for_advice/,author=/u/1nk4bl3,date=2021-01-31T12:38:26Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Can uber eats driver park as many times as they need on time restricted car parks?,id=t3_l9bizy,link=https://www.reddit.com/r/AskUK/comments/l9bizy/can_uber_eats_driver_park_as_many_times_as_they/,author=/u/SnooJokes3907,date=2021-01-31T12:38:26Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=[IN] - Periyar Tiger Reserve trains abandoned tiger cub | The Hindu,id=t3_l9bj3j,link=https://www.reddit.com/r/AutoNewspaper/comments/l9bj3j/in_periyar_tiger_reserve_trains_abandoned_tiger/,author=/u/AutoNewspaperAdmin,date=2021-01-31T12:38:39Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Wait, wha-,id=t3_l9bj3i,link=https://www.reddit.com/r/dankmemes/comments/l9bj3i/wait_wha/,author=/u/sadecenormalbiri,date=2021-01-31T12:38:39Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=[17+] Join The Hood! We’re looking for unique intellectual minds down for some chill time and fun times with deep conversations and light-hearted ones. If you wanna just chill, unwind, and talk about life, memes, philosophy, politics, and even find friendships, you’ll find it with us! See you there!,id=t3_l9bj3f,link=https://www.reddit.com/r/discordserver/comments/l9bj3f/17_join_the_hood_were_looking_for_unique/,author=/u/Holy_Evil,date=2021-01-31T12:38:38Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Shad’s position on the Crying Question: okay for the Croods, not okay for loss of ice cream.,id=t3_l9bj3e,link=https://www.reddit.com/r/MauLer/comments/l9bj3e/shads_position_on_the_crying_question_okay_for/,author=/u/darmodyjimguy,date=2021-01-31T12:38:38Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=[IN] - RJD says in talks with TMC to fight Bengal polls together | The Hindu,id=t3_l9bj39,link=https://www.reddit.com/r/AutoNewspaper/comments/l9bj39/in_rjd_says_in_talks_with_tmc_to_fight_bengal/,author=/u/AutoNewspaperAdmin,date=2021-01-31T12:38:38Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=What are you sad about today?,id=t3_l9bj37,link=https://www.reddit.com/r/AskReddit/comments/l9bj37/what_are_you_sad_about_today/,author=/u/i-dont-use-reddit--,date=2021-01-31T12:38:38Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Ldr Question 2.,id=t3_l9bj35,link=https://www.reddit.com/r/LongDistance/comments/l9bj35/ldr_question_2/,author=/u/Soft_Revenue,date=2021-01-31T12:38:38Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Ariens deluxe staying in drive,id=t3_l9bj34,link=https://www.reddit.com/r/Snowblowers/comments/l9bj34/ariens_deluxe_staying_in_drive/,author=/u/joeybooms,date=2021-01-31T12:38:37Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Eren today...,id=t3_l9bj33,link=https://www.reddit.com/r/titanfolk/comments/l9bj33/eren_today/,author=/u/animeshlego5,date=2021-01-31T12:38:37Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=individual key lightning on a g815,id=t3_l9bj31,link=https://www.reddit.com/r/LogitechG/comments/l9bj31/individual_key_lightning_on_a_g815/,author=/u/beerman2222,date=2021-01-31T12:38:37Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Money doesn't buy happ-,id=t3_l9bj30,link=https://www.reddit.com/r/serbia/comments/l9bj30/money_doesnt_buy_happ/,author=/u/makis560,date=2021-01-31T12:38:37Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Teenage Bottlerocket They Call Me Steve bass cover with lyrics,id=t3_l9bj2v,link=https://www.reddit.com/r/punk/comments/l9bj2v/teenage_bottlerocket_they_call_me_steve_bass/,author=/u/ekvirtanen_bass,date=2021-01-31T12:38:37Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Pink Sweat$ - Honesty (slowed + reverb),id=t3_l9bj2t,link=https://www.reddit.com/r/pinksweats/comments/l9bj2t/pink_sweat_honesty_slowed_reverb/,author=/u/YodasTea,date=2021-01-31T12:38:36Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=I don't want to own physical silver, but I want to get in on the movement. What should I buy?,id=t3_l9bj2q,link=https://www.reddit.com/r/SilverDeals/comments/l9bj2q/i_dont_want_to_own_physical_silver_but_i_want_to/,author=/u/bh999,date=2021-01-31T12:38:36Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Hope they don't loose it...,id=t3_l9bj2p,link=https://www.reddit.com/r/wallstreet/comments/l9bj2p/hope_they_dont_loose_it/,author=/u/dependent_glove_281,date=2021-01-31T12:38:36Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Do Dark Detectors impact adversaries spawns?,id=t3_l9bj2o,link=https://www.reddit.com/r/WizardsUnite/comments/l9bj2o/do_dark_detectors_impact_adversaries_spawns/,author=/u/Electronic-Collar-70,date=2021-01-31T12:38:36Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Pinned to CALAVERAS TATUAJES on Pinterest,id=t3_l9bj2j,link=https://www.reddit.com/r/Calaveras/comments/l9bj2j/pinned_to_calaveras_tatuajes_on_pinterest/,author=/u/CalaverasTienda,date=2021-01-31T12:38:36Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Raikou now 10 players,id=t3_l9bj2k,link=https://www.reddit.com/r/PokemonGoFriends/comments/l9bj2k/raikou_now_10_players/,author=/u/jayhaynes,date=2021-01-31T12:38:36Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Turiporcello,id=t3_l9bj2i,link=https://www.reddit.com/r/OlimpoDeiTURIscepoli/comments/l9bj2i/turiporcello/,author=/u/pippoxviii,date=2021-01-31T12:38:36Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Picasso The Communist Millionaire,id=t3_l9bj2h,link=https://www.reddit.com/r/HowToDraw101/comments/l9bj2h/picasso_the_communist_millionaire/,author=/u/finnagains,date=2021-01-31T12:38:35Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Antique world map, ravensburger 5000 pieces. Did this one a few years ago, will take it apart and start it again soon! You get my brother's foot for scale.,id=t3_l9bj2f,link=https://www.reddit.com/r/Jigsawpuzzles/comments/l9bj2f/antique_world_map_ravensburger_5000_pieces_did/,author=/u/Lulu_Altair,date=2021-01-31T12:38:35Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Top 60 ASMR videos on YouTube last week (2021-01-17 to 2021-01-23) [Discussion],id=t3_l9bj2e,link=https://www.reddit.com/r/asmr/comments/l9bj2e/top_60_asmr_videos_on_youtube_last_week_20210117/,author=/u/Hayate-kun,date=2021-01-31T12:38:35Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Oil-proof Waterproof Stickers Aluminum Foil,id=t3_l9bj2a,link=https://www.reddit.com/r/Home/comments/l9bj2a/oilproof_waterproof_stickers_aluminum_foil/,author=/u/jukiMM,date=2021-01-31T12:38:35Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Still holding strong \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80,id=t3_l9bj29,link=https://www.reddit.com/r/dogecoin/comments/l9bj29/still_holding_strong/,author=/u/Creative-Town-3576,date=2021-01-31T12:38:35Z}",
    "Struct{feed=Struct{title=newest submissions : reddit.com,url=https://www.reddit.com/new/.rss?sort=new},title=Протесты 31 января: - Акции протеста проводятся по всей России несмотря на жесткое давление, запугивание и прямое насилие со стороны властей (обзор по городам),id=t3_l9bj27,link=https://www.reddit.com/r/liberta/comments/l9bj27/протесты_31_января_акции_протеста_проводятся_по/,author=/u/Zobakin,date=2021-01-31T12:38:34Z"
  )
}